### ISSUE TITLE
Issues with Sodium

### ISSUE THREAD

**Issue by fennecr** [ArubikU/MagicShaders#1]
Causes all addons to be on the wrong axis for the player when using sodium. Capes clip through the arm, chest appears on back, and I have not tested wings.
![image](https://github.com/user-attachments/assets/1fe651b7-e6b4-4a87-bc8b-efb385cb9b65)

You can add support for sodium using this mod, though it needs to be worked on in order for it do function.
https://modrinth.com/mod/sodium-core-shader-support

**Comment by ArubikU** [comment]
Its was added
